### ISSUE TITLE
[Feature]: Add griefprevention support

### ISSUE THREAD

**Issue by mastachef** [spnda/BlockProt#260] opened 2024-02-01 19:17 UTC
### Feature description

Would be a nice feature to be able to make it so people who have claims in griefprevention are the only ones who can lock blocks/chests in their claims

https://www.spigotmc.org/resources/griefprevention.1884/

**Comment by spnda** [comment] 2024-02-01 19:20
Duplicate of #154

**Closed by spnda** 2024-02-01 19:20 UTC
Labels: enhancement
