### ISSUE TITLE
[Bug]: Paste configuration doesn't work

### ISSUE THREAD

**Issue by skippytheraket** [spnda/BlockProt#161] opened 2022-06-07 07:15 UTC
### Version of BlockProt

1.0.7

### Description of the bug

The paste configuration doesn't work.

Scenario:
Friend gave me access to chest A, then 'paste configuration' chest A to chest B, C and D.
However, I could only open chest A.
Friend had to manually give me access on chest B for me to access it.
That means it would be tedious if we had to give access to players 1 by 1, hope that makes sense

### Steps to reproduce

1. Fix the Paste Configuration Function

**Comment by spnda** [comment] 2022-06-08 15:01
Probably a duplicate of #123. However, is this only an issue with friends? I'm testing with redstone settings and it seems to work there. Will further test today, though!

Also, could you please give me some more context? So Minecraft version and server software (Spigot/Paper/Purpur/...)?

**Comment by spnda** [comment] 2022-06-08 16:52
I just tested this with friends and it does indeed work for me on Spigot on 1.19.

**Closed** 2022-08-29 19:15 UTC
Labels: bug, duplicate
